### ISSUE TITLE
Name undefined with GitHub oAuth

### ISSUE THREAD

**Issue by edde746** [Nico-Mayer/json-bucket#1]
<img width="1440" alt="image" src="https://github.com/Nico-Mayer/json-bucket/assets/86283021/2731c1f2-151f-48c6-8a3a-d6f1720117db">

**Comment by Nico-Mayer** [comment]
Hello, the issue should be resolved. It would be greatly appreciated if you could verify this.

**Comment by edde746** [comment]
Fixed
